<a href="https://colab.research.google.com/github/Kritisha57/Python-for-Data-Science/blob/main/NumPy_Essentials.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NumPy array and Python Lists
heights=[78,65,82,77,74,70]
#If we want to multipky each height by a number, say 3.25, it will throw an error.Let's see-


In [ ]:
heights*3.25

TypeError: ignored

We get this error because in Python we can't multiply a sequence with a non-int number. We need a 'for' loop which is an inefficient method for handling large data. It takes a lot of time to execute a for loop.


In [ ]:
import numpy as np

In [ ]:
arr=np.array(heights)
print(arr*2)

[156 130 164 154 148 140]


So here we see the same operation can be easily executed with NumPy.Also, NumPy arrays are faster than Lists.

NumPy comes with its own set of methods and operations


In [ ]:
first_list=[1,2,3,4,5]
second_list=[6,7,8,9,10]
list_full=first_list+second_list
list_full

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [ ]:
np1=np.array(first_list)
np2=np.array(second_list)
np_sum=np1+np2
np_sum

array([ 7,  9, 11, 13, 15])

The same '+' operator behaves differently for Lists and numpy arrays. In lists it concatenates and in np arrays it adds consecutive elements of two arrays.

In [ ]:
type(np_sum) #This is a n-dimensional array

numpy.ndarray

The key advantage of using NumPy arrays over lists is that arrays allow you to operate over the entire data, unlike lists.
There are two ways to create NumPy arrays, which are mentioned below.

By converting the existing lists or tuples to arrays using np.array

By initialising fixed-length arrays using the NumPy functions



1.   Another feature of NumPy arrays is that they are homogeneous in nature. By homogenous, we mean that all the elements in a NumPy array have to be of the same data type, which could be an integer, float, string, etc.


---







*   Now we will look at operations and functions on 1D arrays



In [ ]:
import random

heights = [int(random.uniform(70, 80)) for _ in range(100)]
print(heights)


[78, 79, 70, 73, 74, 75, 74, 77, 73, 74, 71, 78, 74, 79, 70, 73, 73, 73, 73, 76, 70, 70, 75, 70, 74, 79, 76, 73, 78, 75, 70, 74, 70, 71, 77, 70, 71, 74, 78, 74, 77, 79, 79, 73, 78, 70, 77, 79, 74, 78, 76, 76, 75, 76, 71, 77, 79, 79, 72, 78, 78, 75, 75, 74, 78, 79, 77, 72, 77, 71, 73, 74, 74, 76, 74, 77, 79, 71, 70, 78, 73, 73, 70, 73, 72, 70, 78, 75, 79, 73, 77, 70, 78, 74, 74, 78, 70, 76, 72, 76]


In [ ]:
arr=np.array(heights)
type(arr)

numpy.ndarray

In [ ]:
#Counting the length of numpy array. We have multiple ways of doing it-
# 1. Uisng the len() function
len(arr)


100

In [ ]:
# 2. Using the 'size' method
arr.size


100

In [ ]:
# 3. Using the 'shape' method
arr.shape

(100,)

In [ ]:
# Convert heights from inches to meters
heights_m=arr*0.0254
heights_m

array([1.9812, 2.0066, 1.778 , 1.8542, 1.8796, 1.905 , 1.8796, 1.9558,
       1.8542, 1.8796, 1.8034, 1.9812, 1.8796, 2.0066, 1.778 , 1.8542,
       1.8542, 1.8542, 1.8542, 1.9304, 1.778 , 1.778 , 1.905 , 1.778 ,
       1.8796, 2.0066, 1.9304, 1.8542, 1.9812, 1.905 , 1.778 , 1.8796,
       1.778 , 1.8034, 1.9558, 1.778 , 1.8034, 1.8796, 1.9812, 1.8796,
       1.9558, 2.0066, 2.0066, 1.8542, 1.9812, 1.778 , 1.9558, 2.0066,
       1.8796, 1.9812, 1.9304, 1.9304, 1.905 , 1.9304, 1.8034, 1.9558,
       2.0066, 2.0066, 1.8288, 1.9812, 1.9812, 1.905 , 1.905 , 1.8796,
       1.9812, 2.0066, 1.9558, 1.8288, 1.9558, 1.8034, 1.8542, 1.8796,
       1.8796, 1.9304, 1.8796, 1.9558, 2.0066, 1.8034, 1.778 , 1.9812,
       1.8542, 1.8542, 1.778 , 1.8542, 1.8288, 1.778 , 1.9812, 1.905 ,
       2.0066, 1.8542, 1.9558, 1.778 , 1.9812, 1.8796, 1.8796, 1.9812,
       1.778 , 1.9304, 1.8288, 1.9304])

In [ ]:
weights_pounds = [int(random.uniform(80, 300)) for _ in range(100)]
weights_lb=np.array(weights_pounds)

In [ ]:
weight_kg=weights_lb*0.453592

In [ ]:
#Calculate BMI

bmi=weight_kg/heights_m**2
bmi


array([17.33404847, 15.43349685, 20.80510324, 20.71342352, 16.30565445,
       16.49868601, 27.47566971, 20.2774161 , 11.87393705, 36.84821124,
       35.56488724, 13.40499749, 14.50818073, 11.94124574, 12.91351236,
       23.7478741 , 17.54704031, 28.89324683, 14.90838763, 32.74334533,
       23.9617396 , 12.33957848, 34.49725257, 15.78318177, 17.71795523,
       16.22206968, 18.86698337, 21.90081723, 25.07659013, 23.62311861,
       28.12276025, 34.15200066, 42.32762384, 26.49932775, 21.93755543,
       21.23555365, 28.59137994, 31.45579008, 14.09835943, 19.13025601,
       33.55853074, 15.99676316, 18.13717513, 33.51088901, 19.29857397,
       22.9573553 , 15.05983535, 10.47675334, 16.43404543, 28.4278395 ,
       28.60478124, 11.4419125 , 16.62367606, 32.01301049, 23.70992483,
       12.9253705 , 22.98126538, 17.91186861, 15.59663112, 23.34318528,
       22.64982334, 18.24854665, 21.62327788, 16.04887249, 24.38322819,
       12.27920552, 14.82267259, 18.17346582, 11.73955669, 22.87

In the BMI example given above, if you had been working with lists, then you would have needed to map a lambda function (or worse, write a for loop). Whereas, with NumPy, you simply use the relevant operators, as NumPy does all the back-end coding on its own.

<font color="red">Subsets in NumPy arrays</font>


In [ ]:
#Indexing and slicing in 1D arrays are similar to those of python lists
#We can also do conditional subsetting

bmi>25

array([False, False, False, False, False, False,  True, False, False,
        True,  True, False, False, False, False, False, False,  True,
       False,  True, False, False,  True, False, False, False, False,
       False,  True, False,  True,  True,  True,  True, False, False,
        True,  True, False, False,  True, False, False,  True, False,
       False, False, False, False,  True,  True, False, False,  True,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False,  True,
       False,  True,  True, False, False, False,  True, False, False,
        True, False,  True,  True,  True,  True,  True, False, False,
       False, False,  True,  True, False, False,  True,  True, False,
        True])

In [ ]:
#Masking: In the previous code block, bmi>25 gave us a boolean array which needs to be masked on the bmi array to get the values
# which satisfy the condition, i.e, where the value is True
bmi[bmi>25]

array([27.47566971, 36.84821124, 35.56488724, 28.89324683, 32.74334533,
       34.49725257, 25.07659013, 28.12276025, 34.15200066, 42.32762384,
       26.49932775, 28.59137994, 31.45579008, 33.55853074, 33.51088901,
       28.4278395 , 28.60478124, 32.01301049, 32.6113089 , 33.3519577 ,
       30.17188029, 35.15345031, 27.04618995, 36.28147433, 26.71770722,
       31.85333048, 27.96559821, 37.37202362, 32.24133016, 27.98923363,
       32.28378089, 31.28267565, 28.11789135])

In [ ]:
#Some other numpy methods for 1D array
bmi.min()
bmi.max()
bmi.mean()

21.735406567847576

<font color="red">Multidimensional NumPy arrays</font>


In [ ]:
import random
players = [(int(random.uniform(50, 90)), int(random.uniform(50, 90))) for _ in range(100)]
players


[(55, 65),
 (80, 52),
 (58, 50),
 (62, 79),
 (80, 87),
 (87, 86),
 (60, 83),
 (54, 87),
 (75, 86),
 (82, 53),
 (86, 87),
 (89, 54),
 (86, 70),
 (74, 83),
 (70, 87),
 (71, 69),
 (75, 60),
 (65, 69),
 (58, 50),
 (71, 73),
 (64, 71),
 (77, 53),
 (83, 71),
 (67, 68),
 (54, 59),
 (71, 80),
 (53, 75),
 (59, 70),
 (61, 53),
 (65, 87),
 (57, 81),
 (83, 64),
 (78, 56),
 (75, 81),
 (86, 89),
 (88, 72),
 (55, 59),
 (59, 52),
 (53, 78),
 (83, 87),
 (51, 68),
 (74, 70),
 (59, 81),
 (57, 79),
 (78, 74),
 (85, 56),
 (57, 88),
 (56, 59),
 (62, 78),
 (61, 58),
 (66, 59),
 (84, 64),
 (72, 55),
 (58, 67),
 (75, 53),
 (75, 66),
 (84, 71),
 (73, 89),
 (63, 63),
 (57, 66),
 (72, 72),
 (57, 73),
 (79, 85),
 (88, 86),
 (60, 79),
 (67, 66),
 (50, 72),
 (54, 85),
 (57, 70),
 (81, 81),
 (85, 55),
 (50, 55),
 (80, 64),
 (85, 59),
 (57, 84),
 (81, 74),
 (67, 55),
 (73, 75),
 (68, 87),
 (76, 61),
 (53, 81),
 (50, 87),
 (75, 87),
 (54, 75),
 (61, 60),
 (50, 66),
 (51, 88),
 (65, 83),
 (66, 56),
 (62, 61),
 (84, 60),

In [ ]:
players[2][1]

50

In [ ]:
import numpy as np
np_players=np.array(players)

In [ ]:
type(np_players)

numpy.ndarray

<font color="blue" size="2">Attributes of 2D NumPy arrays</font>


In [ ]:
#Structure of 2D array
np_players.shape

(100, 2)

In [ ]:
#Dimensions of 2D array
np_players.ndim

2

In [ ]:
#Datatype of elements in the array
np_players.dtype

dtype('int64')

In [ ]:
#Size of single item of the 2D array
np_players.itemsize

8

In [ ]:
# Convert heights to meters and weights to kg

np_players_converted=np_players * [0.0254,0.4535]
np_players_converted

array([[ 1.397 , 29.4775],
       [ 2.032 , 23.582 ],
       [ 1.4732, 22.675 ],
       [ 1.5748, 35.8265],
       [ 2.032 , 39.4545],
       [ 2.2098, 39.001 ],
       [ 1.524 , 37.6405],
       [ 1.3716, 39.4545],
       [ 1.905 , 39.001 ],
       [ 2.0828, 24.0355],
       [ 2.1844, 39.4545],
       [ 2.2606, 24.489 ],
       [ 2.1844, 31.745 ],
       [ 1.8796, 37.6405],
       [ 1.778 , 39.4545],
       [ 1.8034, 31.2915],
       [ 1.905 , 27.21  ],
       [ 1.651 , 31.2915],
       [ 1.4732, 22.675 ],
       [ 1.8034, 33.1055],
       [ 1.6256, 32.1985],
       [ 1.9558, 24.0355],
       [ 2.1082, 32.1985],
       [ 1.7018, 30.838 ],
       [ 1.3716, 26.7565],
       [ 1.8034, 36.28  ],
       [ 1.3462, 34.0125],
       [ 1.4986, 31.745 ],
       [ 1.5494, 24.0355],
       [ 1.651 , 39.4545],
       [ 1.4478, 36.7335],
       [ 2.1082, 29.024 ],
       [ 1.9812, 25.396 ],
       [ 1.905 , 36.7335],
       [ 2.1844, 40.3615],
       [ 2.2352, 32.652 ],
       [ 1.397 , 26.7565],
 

<font color="red" size="2">subsets in 2D NumPy arrays</font>


In [ ]:
# Fetch 1st row of the array
np_players[0]

array([55, 65])

In [ ]:
# Fetch 1st row 1st element
np_players[0][0]

55

In [ ]:
# Fetch 1st column from array
np_players[:,0]

array([55, 80, 58, 62, 80, 87, 60, 54, 75, 82, 86, 89, 86, 74, 70, 71, 75,
       65, 58, 71, 64, 77, 83, 67, 54, 71, 53, 59, 61, 65, 57, 83, 78, 75,
       86, 88, 55, 59, 53, 83, 51, 74, 59, 57, 78, 85, 57, 56, 62, 61, 66,
       84, 72, 58, 75, 75, 84, 73, 63, 57, 72, 57, 79, 88, 60, 67, 50, 54,
       57, 81, 85, 50, 80, 85, 57, 81, 67, 73, 68, 76, 53, 50, 75, 54, 61,
       50, 51, 65, 66, 62, 84, 72, 74, 56, 51, 78, 82, 78, 83, 84])

In [ ]:
# Find height of 12th player
np_players_converted[11][0]

2.2605999999999997

In [ ]:
# Alternate way to find height of 12th player
np_players_converted[11,0]

2.2605999999999997

In [ ]:
possible_skills = ['batsman', 'bowler', 'keeper', 'batsman-keeper', 'all-rounder', 'fielder', 'spin bowler', 'pace bowler', 'wicket-keeper']
skills = np.random.choice(possible_skills, size=100)
print(skills)
np_players_converted[skills=='batsman']


['batsman-keeper' 'batsman' 'batsman-keeper' 'pace bowler' 'batsman'
 'all-rounder' 'fielder' 'bowler' 'keeper' 'bowler' 'fielder'
 'all-rounder' 'bowler' 'all-rounder' 'pace bowler' 'batsman-keeper'
 'batsman-keeper' 'all-rounder' 'spin bowler' 'bowler' 'bowler'
 'pace bowler' 'pace bowler' 'spin bowler' 'spin bowler' 'bowler'
 'batsman-keeper' 'pace bowler' 'pace bowler' 'batsman' 'pace bowler'
 'batsman' 'wicket-keeper' 'fielder' 'fielder' 'batsman-keeper'
 'wicket-keeper' 'bowler' 'batsman' 'pace bowler' 'fielder' 'fielder'
 'all-rounder' 'wicket-keeper' 'fielder' 'batsman-keeper' 'all-rounder'
 'fielder' 'bowler' 'batsman-keeper' 'batsman' 'bowler' 'batsman-keeper'
 'bowler' 'all-rounder' 'bowler' 'all-rounder' 'all-rounder' 'fielder'
 'pace bowler' 'spin bowler' 'batsman-keeper' 'pace bowler' 'batsman'
 'keeper' 'bowler' 'fielder' 'fielder' 'spin bowler' 'pace bowler'
 'keeper' 'pace bowler' 'batsman-keeper' 'batsman-keeper' 'keeper'
 'wicket-keeper' 'batsman' 'keeper' 'batsman-k

array([[ 2.032 , 23.582 ],
       [ 2.032 , 39.4545],
       [ 1.651 , 39.4545],
       [ 2.1082, 29.024 ],
       [ 1.3462, 35.373 ],
       [ 1.6764, 26.7565],
       [ 2.2352, 39.001 ],
       [ 1.7018, 24.9425],
       [ 1.9812, 24.0355]])



*   Other ways of creating NumPy arrays are:
        np.ones(): It is used to create an array of 1s.

        np.zeros(): It is used to create an array of 0s.

        np.random.randint(): It is used to create a random array of integers within a particular range.

        np.random.random(): It is used to create an array of random numbers.

        np.arange(): It is used to create an array with increments of fixed step size.

        np.linspace(): It is used to create an array of fixed length.
        np.full(): It is used to create a constant array of any number ‘n’.

        np.tile(): It is used to create a new array by repeating an existing
         array for a particular number of times.
         
        np.eye(): It is used to create an identity matrix of any dimension



In [ ]:
help(np.ones)

Help on function ones in module numpy:

ones(shape, dtype=None, order='C', *, like=None)
    Return a new array of given shape and type, filled with ones.
    
    Parameters
    ----------
    shape : int or sequence of ints
        Shape of the new array, e.g., ``(2, 3)`` or ``2``.
    dtype : data-type, optional
        The desired data-type for the array, e.g., `numpy.int8`.  Default is
        `numpy.float64`.
    order : {'C', 'F'}, optional, default: C
        Whether to store multi-dimensional data in row-major
        (C-style) or column-major (Fortran-style) order in
        memory.
    like : array_like, optional
        Reference object to allow the creation of arrays which are not
        NumPy arrays. If an array-like passed in as ``like`` supports
        the ``__array_function__`` protocol, the result will be defined
        by it. In this case, it ensures the creation of an array object
        compatible with that passed in via this argument.
    
        .. versionad

In [ ]:
arr=np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [ ]:
arr.dtype

dtype('float64')

In [ ]:
arr_int=np.ones(5,dtype=int)

In [ ]:
arr_int.dtype

dtype('int64')

In [ ]:
np.ones([5,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.ones([5,3],dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
# Creating arrays with range and arange functions
list(range(1,10))

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [ ]:
np.arange(5.0)

array([0., 1., 2., 3., 4.])

In [ ]:
np.arange(3,36,3)

array([ 3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33])

In [ ]:
# Generating random integer array
np.random.randint(3,7,size=10)

array([6, 3, 3, 5, 6, 5, 5, 6, 4, 3])

In [ ]:
np.random.randint(4,size=7)

array([2, 0, 3, 2, 3, 0, 3])

In [ ]:
# Creating 2D array using random function
np.random.random([3,4])

array([[0.55404116, 0.15458019, 0.72996572, 0.10590016],
       [0.41294158, 0.62993523, 0.37764495, 0.34505081],
       [0.80416535, 0.63391233, 0.44464993, 0.01049898]])

In [ ]:
# Creating array of fixed length
np.linspace(1,10,20)

array([ 1.        ,  1.47368421,  1.94736842,  2.42105263,  2.89473684,
        3.36842105,  3.84210526,  4.31578947,  4.78947368,  5.26315789,
        5.73684211,  6.21052632,  6.68421053,  7.15789474,  7.63157895,
        8.10526316,  8.57894737,  9.05263158,  9.52631579, 10.        ])

<font color="red"><b><small>Mathematical Operations in NumPy arrays</small></b></font>


Manipulate arrays

    Reshape arrays
    Stack arrays
Perform operations on arrays

    Perform basic mathematical operations

      Power
      Absolute
      Trigonometric
      Exponential and logarithmic

Apply built-in functions

Apply your own functions

Apply basic linear algebra operations

In [ ]:
array1=np.arange(1,10)
array2=np.arange(7,16)

In [ ]:
array1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
array2

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])

In [ ]:
array3=array1+array2
array3

array([ 8, 10, 12, 14, 16, 18, 20, 22, 24])

In [ ]:
array4=np.array([1,2,3,4,5])


In [ ]:
arr=array4+array1 #We cannt add arrays of different sizes

ValueError: ignored

We cannot add numpy arrays of different shape. A point to note here is that when the shapes of NumPy arrays are not the same, the arrays cannot be operated on. Because of this restriction on the operability, the flexibility of NumPy reduces significantly. Fortunately, the developers of NumPy noticed this issue and developed a few functions that can modify the shape of a NumPy array.

In [ ]:
#np.hstack() and np.vstack are used to stack the arrays horizontally and vertically
arr1=np.array([1,2,3])
arr2=np.array([2,3,4])
# For hstack, number of rows should be the same and for vstack number of columns must be same

In [ ]:
np.hstack([arr1,arr2])

array([1, 2, 3, 2, 3, 4])

In [ ]:
np.vstack([arr1,arr2])

array([[1, 2, 3],
       [2, 3, 4]])

In [ ]:
# Implementation of reshape()

a=np.arange(12).reshape(3,4)
b=np.arange(20).reshape(5,4)
print(a)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [ ]:
np.vstack([a,b])

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [ ]:
np.arange(132).reshape(11,12)

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11],
       [ 12,  13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23],
       [ 24,  25,  26,  27,  28,  29,  30,  31,  32,  33,  34,  35],
       [ 36,  37,  38,  39,  40,  41,  42,  43,  44,  45,  46,  47],
       [ 48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71],
       [ 72,  73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83],
       [ 84,  85,  86,  87,  88,  89,  90,  91,  92,  93,  94,  95],
       [ 96,  97,  98,  99, 100, 101, 102, 103, 104, 105, 106, 107],
       [108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131]])

if you have an array 'p', reshaping it as np.reshape(p,-1) will give a 1-D array


In [ ]:
m=np.array([[1, 2, 3, 4, 5],
 [6, 7, 8, 9, 10],
 [11, 12, 13, 14, 15],
 [16, 17, 18, 19, 20]])

# Expected output:
#  [[1, 3]
#  [5, 7]
#  [9, 11]
#  [13, 15]
#  [17, 19]]

In [ ]:
print(m[m%2 != 0].reshape(5, 2))

[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]
 [17 19]]


In [ ]:
p=np.array([[1, 5],
 [3, 7],
 [4, 9]])

np.reshape(p, (1, -1))# This will give a 2D array

array([[1, 5, 3, 7, 4, 9]])

In [ ]:
# Trignometric functions
np.pi

3.141592653589793

In [ ]:
theta=np.linspace(0,np.pi,5)

In [ ]:
sine=np.sin(theta)
sine

array([0.00000000e+00, 7.07106781e-01, 1.00000000e+00, 7.07106781e-01,
       1.22464680e-16])

In [ ]:
cosine=np.cos(theta)
cosine

array([ 1.00000000e+00,  7.07106781e-01,  6.12323400e-17, -7.07106781e-01,
       -1.00000000e+00])

In [ ]:
# Exponential and Logarithmic function
x=np.array([1,2,3,10])
np.exp(x)


array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 2.20264658e+04])

In [ ]:
# 2^1,2^2,2^3,2^10

np.exp2(theta)

array([1.        , 1.72356793, 2.97068642, 5.12017986, 8.82497783])

In [ ]:
np.power(x,3)

array([   1,    8,   27, 1000])

In [ ]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 2.30258509])

In [ ]:
np.log2(x)

array([0.        , 1.        , 1.5849625 , 3.32192809])

In [ ]:
np.log10(x)

array([0.        , 0.30103   , 0.47712125, 1.        ])

In [ ]:
# Important concept
x=np.arange(5)
y=np.zeros(10)
print(x)
print(y)


[0 1 2 3 4]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [ ]:
np.power(2,x,out=y[::2])

array([ 1.,  2.,  4.,  8., 16.])

In [ ]:
y

array([ 1.,  0.,  2.,  0.,  4.,  0.,  8.,  0., 16.,  0.])

In [ ]:
# Aggregate function
x=np.arange(1,10)

In [ ]:
sum(x)

45

In [ ]:
np.add.reduce(x)

45

In [ ]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [ ]:
np.multiply.reduce(x)

362880

In [ ]:
np.multiply.accumulate(x)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880])

<span style="color:red; font-size:small; font-weight:bold;">Linear Algebra Functions in NumPy</span>


In [ ]:
mat=np.array([[6,1,1],[4,-2,5],[2,8,7]])
mat

array([[ 6,  1,  1],
       [ 4, -2,  5],
       [ 2,  8,  7]])

In [ ]:
np.linalg.matrix_rank(mat)

3

In [ ]:
mat_inv=np.linalg.inv(mat)
mat_inv

array([[ 0.17647059, -0.00326797, -0.02287582],
       [ 0.05882353, -0.13071895,  0.08496732],
       [-0.11764706,  0.1503268 ,  0.05228758]])

In [ ]:
np.matmul(mat,mat_inv)

array([[ 1.00000000e+00,  0.00000000e+00,  2.77555756e-17],
       [-1.38777878e-17,  1.00000000e+00,  1.38777878e-17],
       [-4.16333634e-17,  1.38777878e-16,  1.00000000e+00]])

In [ ]:
mat*mat_inv # Element wise multiplication

array([[ 1.05882353, -0.00326797, -0.02287582],
       [ 0.23529412,  0.26143791,  0.4248366 ],
       [-0.23529412,  1.20261438,  0.36601307]])

In [ ]:
np.linalg.matrix_power(mat,3)

array([[336, 162, 228],
       [406, 162, 469],
       [698, 702, 905]])

In [ ]:
import numpy as np
np.arange(1,65).reshape(8,8)

array([[ 1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16],
       [17, 18, 19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30, 31, 32],
       [33, 34, 35, 36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45, 46, 47, 48],
       [49, 50, 51, 52, 53, 54, 55, 56],
       [57, 58, 59, 60, 61, 62, 63, 64]])